#Seeing the world
dream_land=['France','Spain','Germany','Italy','England']
print("original list")
print(dream_land)
print("alphabetical order using sorted so as not to change the order of the list")
print(sorted(dream_land))
print("showing list is still in original order")
print(dream_land)
print("reverse alphabetical order using sorted so as not to change the order of the list")
print(sorted(dream_land, reverse=True))
print("showing list is still in original order")
print(dream_land)
print("using reverse to change the order of the list")
dream_land.reverse()
print(dream_land)
print("reversing again to change its order")
dream_land.reverse()
print(dream_land)
print("using sort to arrange in alphabetical order")
dream_land.sort()
print(dream_land)
print("using sort to arrange in reverse alphabetical order")
dream_land.sort(reverse=True)
print(dream_land)

